databases:
  - name: ERPMindDB
    plan: free
    databaseName: erpmind
    user: erpmind

services:
  - type: web
    plan: free
    name: ERPMind
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn ERPMind.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ERPMindDB
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4